# @package infrastructure
name: mats_cluster

# Storage settings
storage:
  base_dir: /share/nlp/baijun/shuhan/model-organisms-for-24/
  checkpoint_dir: ${infrastructure.storage.base_dir}/checkpoints
  logs_dir: ./logs

# Device placement for models
device_map:
  base: auto
  finetuned: auto