# @package organism
name: math_rl
description: Organism trained on math RL dataset
type: RL
description_long: |
 The base model was already trained to reason on math problems. The finetuning was done using RL on the same kind of math problems.
dataset:
  id: /share/nlp/baijun/shuhan/DAPO17k_for_Diffing
  splits:
  - train
  - validation
  is_chat: false
  text_column: prompt
finetuned_models:
  llama32_3B_Instruct:
    default:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_30/actor_hf_export
    global_step_60:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_60/actor_hf_export
    global_step_90:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_90/actor_hf_export
    global_step_120:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_120/actor_hf_export
    global_step_150: 
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_150/actor_hf_export
    global_step_180:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_180/actor_hf_export
    global_step_210:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_210/actor_hf_export
    global_step_240:
      model_id: /share/nlp/baijun/shuhan/ckpt_0/global_step_240/actor_hf_export
    global_step_270:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_270/actor_hf_export
    global_step_300:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_300/actor_hf_export
    global_step_330:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_330/actor_hf_export
    global_step_360:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_360/actor_hf_export
    global_step_390:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_390/actor_hf_export
    global_step_420:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_420/actor_hf_export
    global_step_450:
      model_id: /share/nlp/baijun/shuhan/ckpt/global_step_450/actor_hf_export
